README.md
add_me_to_your_PATH/Dockerfile.template
add_me_to_your_PATH/accounts.sh
add_me_to_your_PATH/build_image
add_me_to_your_PATH/driver.yaml.template
add_me_to_your_PATH/julia_pod
add_me_to_your_PATH/sysimage.jl

Uses [`github-token-helper`](https://github.com/beacon-biosignals/github-token-helper) to avoid embedding the secrets in the image layers. Additional changes include:
- Conditionally set a private package registry via `--build-arg PRIVATE_REGISTRY_URL=...`
- Conditionally install Revise and Pprof via the build arg `ADD_UTILS`
- Skip installing PackageCompiler and attempting to make a system image if no packages are to be included in the system image
- Replace the default system image when using `create_sysimage`. This makes it easier to handle the previous point. The original system image can be restored via PackageCompilers normal mechanisms
TODO:

Use Docker build secrets

---

add_me_to_your_PATH/Dockerfile.template

This is easier explained with an example. Let's say I have AWSS3.jl and AWS.jl in my Project.toml, and I was working on AWS.jl so I un-pinned it so that I don't build it into my sysimage, because I want to be able to change versions (e.g. switch to my branch) without rebuilding it. Currently, we would `rm` AWS.jl from the Project before building the sysimage. But we would *not* rm AWSS3, which means that AWSS3 and *all of its dependencies* including AWS.jl would get baked into the sysimage. That means I would not be able to change versions of AWS.jl despite unpinning it.
Here, we use a Pkg command to remove the packages everywhere in the Manifest. That means if any package depends on a removed package, it is removed too. So in the example, we would not build either AWSS3 or AWS into the …

Remove non-pinned packages more thoroughly

---

README.md
add_me_to_your_PATH/julia_pod

I've noticed that running notebooks on k8s is a nice way to share the same session across users, as long as they have permissions for the same namespace.
So I added a `--port-forward` option to `julia_pod`, with an example for spinning up a Pluto notebook in the README.

--port-forward flag

---

README.md
add_me_to_your_PATH/julia_pod

I was getting errors that the job name was too long (using `--image` with a long image name that includes the ECR url), so I needed this to choose a shorter one.

allow customizing the RUNID variable

---

add_me_to_your_PATH/Dockerfile.template

The `sysimage-image` build stage in `Dockerfile.template` depends on a docker `base` stage, which can be cached containing stale registry metadata. This can lead to build failure on `Pkg.instantiate` if updated package versions are no longer compatible with the stale registry metadata.
This tiny fix calls `Pkg.Registry.update()` before `Pkg.instantiate()` in the `sysimage-image` stage.

update registries before Pkg.instantiate

---

add_me_to_your_PATH/Dockerfile.template

without re-running julia precompile.
This makes the behaviour of `julia_pod` more consistent
between when `--no-sync` is passed in and when it isn't,
and makes it so that all the files that are synced by
`devsync` are there in the pod before the julia session starts.

COPY ./* /JuliaProject/  at end of build

---

add_me_to_your_PATH/build_image
add_me_to_your_PATH/sysimage.jl

PackageCompiler v2 no longer lets you replace the default julia sysimage. Upgrading to PackageCompiler v2 would require changing the `Dockerfile.template` to add a `--sysimage-...` to the `julia` invocations, or to set a `docker exec`-friendly equivalent of an alias.

use packagecompiler v1

---

add_me_to_your_PATH/driver.yaml.template

YAML will interpret unquoted values that are entirely number characters as a number, and otherwise as a string. This can cause julia_pod to fail if a string is expected downstream and an interpolated value just so happens to contain only numbers. This quotes all the interpolated values that should be strings.

Bugfix: quote strings

---

add_me_to_your_PATH/Dockerfile.template
add_me_to_your_PATH/driver.yaml.template

Turns out using `*` makes a flat copy of files. We want to maintain the directory structure of the project, so we should use `.` instead. (Branched from my other PR, so that one should probably merge first).

Bugfix: DOCKER copy

---

add_me_to_your_PATH/Dockerfile.template

Docker linting in VSCode indicates that a trailing `/` should be used in the directory being copied to (when copying an entire directory

fix: add trailing `/`

---

add_me_to_your_PATH/Dockerfile.template

Currently Revise and PProf are never installed, because the `if [ "$ADD_UTILS" == true ]` is an error in sh (needs to be `=` with single `[`, adn `[[` are not available in sh where this step is happening).

shell `if [` uses `=` not `==` for comparison

---

README.md

@kevinzzheng and I just spent a while wondering why we weren't able to push images, turns out that the `IMAGE_REPO` was set to just the ECR repo name, instead of the whole URI with the account ID etc. The docs were not super clear!

Add note about IMAGE_REPO

---

README.md
add_me_to_your_PATH/Dockerfile.template
add_me_to_your_PATH/build_image
add_me_to_your_PATH/julia_pod
add_me_to_your_PATH/startup.jl

This moves the `Dockerfile`, default `driver.yaml.template` and generated `driver-*.yaml` into the local `julia_pod/`, for sanity.
Now all local julia_pod-related files are tucked away in `julia_pod/`.

`mv Dockerfile driver* julia_pod/.`

---

add_me_to_your_PATH/julia_pod

This PR is one possible fix for #50: before adding the datetime stamp (which adds 12 characters, `-dddHHhMMmSS`) and the random hex (7 characters, `-XXXXXX`), this truncates the RUNID to be at most 44 characters so that the job name will always be 63 characters or fewer (44 + 12 + 7).
IIUC, this should still be compatible with things like K8sClusterManagers.jl which use `generateName` since that does its own truncation.

truncate RUNIDs to 44 chars before adding time and random hex

---

README.md
add_me_to_your_PATH/build_image
add_me_to_your_PATH/julia_pod

this is useful for minikube, where you can directly build using the minikube docker instead of setting up and pushing to a dummy registry.
See [here](https://minikube.sigs.k8s.io/docs/handbook/pushing/#1-pushing-directly-to-the-in-cluster-docker-daemon-docker-env) for the minikube instructions about how to directly build inside minikube. 
I tested them locally and could speed up my build process significantly:
- With push, after stopping and restarting minikube, the images (several GB) need to be send to the minikube cluster again. This is a common case, kind of every day, as I like to stop the minikube if I don't need it. 
- Without push (i.e. with the new `--no-push` enabled), no pushing is needed and the cache of the minikube docker can be successfully used. julia_pod is super fast …

feat: option --no-push

---

README.md
add_me_to_your_PATH/Dockerfile.template
add_me_to_your_PATH/driver.yaml.template
add_me_to_your_PATH/julia_pod

The `julia_pod` feature to allow easy interactive adding of private packages uses a K8s secret to store the user's GitHub PAT. The K8s secret could be read by anyone with access to the namespace which has the potential to leak the GitHub PAT to malicious actors. This PR removes this feature but preserves the ability to use private Julia packages during the image build.
Supersedes: #56

Remove use of K8s secret to store GitHub PAT

---

add_me_to_your_PATH/Dockerfile.template

Follow up to #60. Uses a newer version of `github-token-helper` which doesn't result in a failure when interactively adding package when a private registry is present:
```
(JuliaProject) pkg> add LibPQ
Updating registry at `~/.julia/registries/Private`
Updating git-repo `https://github.com/example/PrivateRegistry`
Specified GitHub token file does not exist: /run/secrets/github_token
ERROR: IOError: write: broken pipe (EPIPE)
Stacktrace:
[1] uv_write(s::Base.PipeEndpoint, p::Ptr{UInt8}, n::UInt64)
@ Base ./stream.jl:1010
[2] unsafe_write(s::Base.PipeEndpoint, p::Ptr{UInt8}, n::UInt64)
@ Base ./stream.jl:1064
[3] unsafe_write(io::Base.Process, p::Ptr{UInt8}, nb::UInt64)
@ Base ./io.jl:362
[4] write
@ ./strings/io.jl:244 [inlined]
...
```
With this change:
```
(JuliaProject) pkg> add LibPQ …
```

Fix inability to add packages interactively

---

add_me_to_your_PATH/Dockerfile.template
add_me_to_your_PATH/sysimage.jl

When adding default Revise and PProf (which are totally arbitrary things to put into the base project environment...), add `preserve=Pkg.PRESERVE_ALL` kwarg per @ssfrr's suggestion.

preserve all

---

.github/workflows/docker.yaml
add_me_to_your_PATH/Dockerfile.template

Depends on #67
Minor changes to the `Dockerfile.template`:
- Provide links to where users can find the valid argument values for `JULIA_VERSION` and `CUDA_VERSION`
- Add comment headers for each stage
- Comment on what the `sysimage-project` stage code is doing
- Make `sysimage.packages` an optional dependency
- Validate that the `julia` executable and CUDA image's have compatible architectures. Without this check it's possible to say accidentally copy in an ARM64 `julia` executable into a AMD64 CUDA container. Mainly, this can occur when one of the referenced images isn't setup as multi-architecture image.
- Reduce output from `apt-get`
- Comment on why system packages are required to be installed
- Avoid showing progress bar when downloading `github-token-helper`
- Use `JULIA_PROJECT` …

Cleanup `Dockerfile.template`

---

add_me_to_your_PATH/Dockerfile.template
add_me_to_your_PATH/sysimage.jl

Depends on #68
Uses a Docker mount cache for storing the Julia depot. The primary advantage of this is that the `~/.julia` directory information can persist between builds allowing for Docker builds with lots of dependencies to build much quicker. As part of incorporating this change I need to review how we were building the system image. Specifically, we no longer have the `project` stage be based off of the `sysimage-image` stage but instead only copy the information it requires from that stage.
I also experimented with making the use of the cache mount when building the system image to be read-only. If we could enable this flag then Docker would allow concurrent access to one locking writer and multiple readers. However, the `sysimage.jl` script does write to …

Use Docker mount cache
